### ISSUE TITLE
Unable to build on android studio v3.0.1

### ISSUE THREAD

**Issue by sarrocks1** [RocketChat/Rocket.Chat.Android#838]
Followed all steps to clone and build on windows 10 , android studio v3.0.1 . Followed both terminal and android studio steps but got following errors-
Error:(11, 2) error: error.NonExistentClass is bound multiple times:
    public abstract void inject(@org.jetbrains.annotations.NotNull()
                         ^
      @org.jetbrains.annotations.NotNull @Singleton @Provides error.NonExistentClass chat.rocket.android.dagger.module.AppModule.provideRocketChatClient(okhttp3.OkHttpClient, error.NonExistentClass, error.NonExistentClass)
      @org.jetbrains.annotations.NotNull @Singleton @Provides error.NonExistentClass chat.rocket.android.dagger.module.AppModule.provideTokenRepository()
      @org.jetbrains.annotations.NotNull @Singleton @Provides error.NonExistentClass chat.rocket.android.dagger.module.AppModule.providePlatformLogger()

Also a compilation error-
Error:Execution failed for task ':app:kaptDebugKotlin'.
> Compilation error. See log for more details
Help Needed!!!
Thanks!!!

**Comment by Shailesh351** [comment]
@sarrocks1 Make sure you have put Rocket.Chat.Kotlin.SDK in the same folder as Rocket.Chat.Android.

And also try release/2.0.0-beta7 which will be merged to develop-2.x soon. develop-2.x is having some conflicts because of SDK change

Thanks!!

**Comment by sarrocks1** [comment]
Both are in the same folder 
 I reduced the number of compilation errors by following build steps again but still the error-
Error:Execution failed for task ':app:kaptDebugKotlin'
still persists.

Thank You!!

**Comment by philipbrito** [comment]
Try to solve this issue through the SDK project. From the SDK project, in the `Gradle` tab (located on the top right side of the IDE) - `rocket.chat.kotlin.sdk`- `Tasks` - `build`, run `assemble` and `build`. Back to the Android project and from the `Build` menu (on Android Studio) select `Rebuild Project`.

**Comment by SyamSundarKirubakaran** [comment]
@sarrocks1 A simple task that developers forget at times, is to clean and build while switching between branches. Try to clean your branch and build it.. It helps..

**Comment by philipbrito** [comment]
Is this issue still valid @sarrocks1 ?

**Comment by sarrocks1** [comment]
Nope @filipedelimabrito .
Apparently , the only solution is to compile on /2.0.0-beta7 branch.
But for the one's who have already done it on the develop-2.x branch , you guys need to first remove whole of the project from android studio and clone it again. That's the way it worked for me.
Thank You!!!
