### ISSUE TITLE
Error in chatroom>presentation>ChatRoomPresenter.Kt

### ISSUE THREAD

**Issue by agampreetsingh** [RocketChat/Rocket.Chat.Android#842]
I have updated to the latest version of Gradle and Android Studio but I am unable to run the project.
I have also cloned the Kotlin SDK in the same directory but the clean and assemble commands don't seem to be working.
Here's a snapshot of my log.

```Information:Gradle tasks [:app:assembleDebug]
Warning:warning: Supported source version 'RELEASE_7' from annotation processor 'org.jetbrains.kotlin.kapt3.ProcessorWrapper' less than -source '1.8'
E:\GSoC\Rocket.Chat.Android\app\src\main\java\chat\rocket\android\chatroom\presentation\ChatRoomPresenter.kt
Error:(151, 27) Classifier 'Authenticating' does not have a companion object, and thus must be initialized here
Error:(152, 27) Classifier 'Connected' does not have a companion object, and thus must be initialized here
Error:(154, 70) Expected 2 parameters of types Boolean, String
Error:(155, 72) Unresolved reference: it
Error:(164, 19) Classifier 'Connected' does not have a companion object, and thus must be initialized here
Error:(166, 62) Expected 2 parameters of types Boolean, String
Error:(167, 64) Unresolved reference: it
E:\GSoC\Rocket.Chat.Android\app\src\main\java\chat\rocket\android\chatrooms\presentation\ChatRoomsPresenter.kt
Error:(102, 27) Classifier 'Authenticating' does not have a companion object, and thus must be initialized here
Error:(103, 27) Classifier 'Connected' does not have a companion object, and thus must be initialized here
Error:(105, 55) Expected 2 parameters of types Boolean, String
Error:(106, 55) Unresolved reference: it
Error:(108, 47) Expected 2 parameters of types Boolean, String
Error:(109, 47) Unresolved reference: it
Error:(118, 19) Classifier 'Connected' does not have a companion object, and thus must be initialized here

[KOTLIN] deleting E:\GSoC\Rocket.Chat.Android\app\build\tmp\kotlin-classes\debug on error
[KOTLIN] deleting E:\GSoC\Rocket.Chat.Android\app\build\tmp\kotlin-classes\debug on error
Information:BUILD FAILED in 3m 5s
Information:14 errors
Information:1 warning
Information:See complete output in console`````

Please Help

**Comment by joeljacobdev** [comment]
@agampreetsingh Please use release/2.0.0-beta7 for now. The develop-2.x branch is currently broken.

**Comment by sarrocks1** [comment]
I had most of  these errors in my first build. I followed the build steps again and now I am getting a single compilation error.
Try building the project again with the given steps might work.
(Build from terminal and not from android studio)
THANK YOU!!!

**Comment by agampreetsingh** [comment]
@sarrocks1 Are you working in develop-2.x branch?

**Comment by sarrocks1** [comment]
@agampreetsingh I am working on release/2.0.0beta now but still the same error .Will post solution as soon as I get it.
Thank You!!!

**Comment by agampreetsingh** [comment]
Thanks @sarrocks1, @pcforgeek  _realease/2.0.0beta_ works just fine. I am working on it now.
@sarrocks1 I hope you resolved it too. Let me know if I can help.
